package com.quiz_app.entity.leaderboard.global;

public enum GlobalRank {
    BEGINNER, NOVICE, AMATEUR, APPRENTICE, LEARNER,
    AVERAGE, COMPETENT, PROFICIENT, SKILLED, EXPERT,
    VETERAN, MASTER, GRANDMASTER, SAGE, GENIUS,
    BRILLIANT, PHENOMENAL, LEGENDARY, IMMORTAL
}
