export const data = [
    // Moc data generated by intellij idea to test front end implementation
    {
        id: 1,
        quizTitle: "Math is Fun",
        tags: "Math",
        status: "verified",
        date: "15 Minutes ago",
    },
    {
        id: 2,
        quizTitle: "Physics is Fun",
        tags: "Physics",
        status: "verified",
        date: "23 Minutes ago",
    },
    {
        id: 3,
        quizTitle: "Sarah Smith", // concatenated the first and last names
        tags: "Math", // added a tag for 'Math' since it's not explicitly mentioned
        status: "Completed", // converted to title case
        date: "1 Hour ago",
    },
    {
        id: 4,
        quizTitle: "Joseph Choo",
        tags: "Math", // added a tag for 'Math' since it's not explicitly mentioned
        status: "Processing", // converted to title case
        date: "1 Hour ago",
    },
    {
        id: 5,
        quizTitle: "Steve Harding",
        tags: "Physics", // added a tag for 'Physics' since it's not explicitly mentioned
        status: "On Hold", // converted to title case
        date: "2 Hour ago",
    },
    {
        id: 6,
        quizTitle: "Laura Croft",
        tags: "Math", // added a tag for 'Math' since it's not explicitly mentioned
        status: "Completed", // converted to title case
        date: "3 Hour ago",
    },
    {
        id: 7,
        quizTitle: "Michael Jones",
        tags: "Math", // added a tag for 'Math' since it's not explicitly mentioned
        status: "Completed", // converted to title case
        date: "3 Hour ago",
    },
    {
        id: 8,
        quizTitle: "James Bond",
        tags: "Physics", // added a tag for 'Physics' since it's not explicitly mentioned
        status: "Completed", // converted to title case
        date: "7 Hour ago",
    },
    {
        id: 9,
        quizTitle: "Haley Whiting",
        tags: "Math", // added a tag for 'Math' since it's not explicitly mentioned
        status: "Completed", // converted to title case
        date: "1 Day ago",
    },
    {
        id: 10,
        quizTitle: "Tim Thomas",
        tags: "Physics", // added a tag for 'Physics' since it's not explicitly mentioned
        status: "Completed", // converted to title case
        date: "1 Day ago",
    },
];
