name: Create Sprint Release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Build with Maven
        run: mvn -B clean package -DskipTests --file pom.xml
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd FrontEnd/interactive-quiz-app && npm ci
      - name: Build Next.js project
        run:  cd FrontEnd/interactive-quiz-app && npm run build
      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      # Added the necessary permissions
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/*.jar,FrontEnd/interactive-quiz-app/.next/**/*"
          body: ${{ steps.changelog.outputs.changelog }}
          #          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          allowUpdates: true
          tag: v0.2.0
          draft: false
          prerelease: false