name: Front-End Build

on:
  pull_request:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd FrontEnd/interactive-quiz-app && npm ci
      - name: Build Next.js project
        run: cd FrontEnd/interactive-quiz-app && npm run build
      - name: Check if build successful
        run: |
          if [ "$?" -ne 0 ]; then
            echo "::error::Build failed!"
            exit 1
          fi
