name: Front-End Build And BackEnd Integration

on:
  pull_request:
    branches:
      #      - trying to fix the issue created by Nuraiya
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Build with Maven
        run: mvn -B clean package -DskipTests --file pom.xml
      - name: Check if build successful
        run: |
          if [ "$?" -ne 0 ]; then
            echo "::error::Build failed!"
            exit 1
          fi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      #      - name: Build Docker image
      #        run: docker build . -t backend-image
      - name: Start backend with Docker Compose
        run: docker-compose up -d
      - name: Wait for backend to start
        run: sleep 60 # adjust this value as needed
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd FrontEnd/interactive-quiz-app && npm ci
      - name: Build Next.js project
        run: cd FrontEnd/interactive-quiz-app && npm run build
      - name: Check if build successful
        run: |
          if [ "$?" -ne 0 ]; then
            echo "::error::Build failed!"
            exit 1
          fi
